### ISSUE TITLE
Lyrics stop after a few lines

### ISSUE THREAD

**Issue by cassidyjames** [naaando/lyrics#10]
Using the 0.2.4 release from AppCenter, it seems that every song only displays the first five or so lines, or perhaps the first 30 seconds or so of the song. After that, the app seems to just stop showing new lines. This was reproducible for me while playing several songs by several artists from the elementary Music app.

**Comment by naaando** [comment]
Haha, I kinda liked of some o' them. 

I believe the rewrite on the parser, display and lyric model fixed the random crashes, and the lyric sorting problem. Many thanks for your feedback and patience! I'll be pushing the new release to AppCenter.
