### ISSUE TITLE
Make the app translatable

### ISSUE THREAD

**Issue by NathanBnm** [naaando/lyrics#14]

**Comment by naaando** [comment]
Hi Nathan, thanks for your care for internationalization and your work around translating eOS apps, I think my last commit solves it, but I'll let it open while I translate it to Portuguese so I may be able to fix any problems that can occur.

**Comment by NathanBnm** [comment]
Thanks! I'm going to translate the app to French.

**Comment by NathanBnm** [comment]
@naaando you just forget to add `data` strings in `appdata.xml` and `.desktop` files :+1:

**Comment by naaando** [comment]
Oh, sure I missed them, I'll add them later.

**Comment by naaando** [comment]
Hey Nathan, `appdata.xml` and `.desktop` added! ;)

**Comment by NathanBnm** [comment]
Great! See #17. Closing.
