### ISSUE TITLE
Font Customization

### ISSUE THREAD

**Issue by geraltofrivia** [naaando/lyrics#16]
Thank you for making this app. I've been on the lookout for something like this since forever. 
I really love the translucent on focus loss (while keeping window above) feature. However, it ends up taking a substantial part on the screen, due to it's large font size. 

If it were possible to change font size, I can make the window much smaller, keep it on a side and keep doing my work, which would be wonderful.

**Comment by naaando** [comment]
Hi, I can add this configuration later, but for now you should be able to customize the font size by CSS on `$HOME/.config/gtk-3.0/gtk.css`

```css
.lyrics .display {
	font-size: 20px;
	font-family: Serif;
}
```

Thank you for the feedback.

**Comment by geraltofrivia** [comment]
Thanks a lot.

**Comment by geraltofrivia** [comment]
Actually, along the same lines, consider removing minimum width, height constraints (or making them configurable).

Cheers

**Comment by naaando** [comment]
@geraltofrivia the version 0.5.2 brings **reduced margin and borders**, **font chooser button** and saves width and height, check it out on [release page](https://github.com/naaando/lyrics/releases) while it don't come to AppCenter! =)
