### ISSUE TITLE
Improve ux

### ISSUE THREAD

**Issue by naaando** [naaando/lyrics#20]
- [ ] Add fade in and fade out on to labels on edges of the window
- [x] Make headerbar transparent when inactive (user shouldn't be able to click on the invisible components too)

**Comment by naaando** [comment]
- Block user scroll

**Comment by naaando** [comment]
Instead of blocking user scroll it should be intercepted to adjust lyric offset

**Comment by SaturnSoftware** [comment]
i think the default gradient on the ui is a bit harsh, could it be softened?

**Comment by naaando** [comment]
Yeah, you can override any of [these css classes](https://github.com/naaando/lyrics/blob/master/data/Application.css) on your current gtk theme, I was working on a theme manager but unfortunately my computer broke. Have in mind that radial and vertical gradients don't fit well, but if you have some good gradients palette I'm open to suggestions ;)
