### ISSUE TITLE
Update appdata translations strings

### ISSUE THREAD

**Issue by NathanBnm** [naaando/lyrics#24]
It seems that the strings in translation files are outdated so they're not translated. Please replace them by the new one in `appdata.xml`.

Also on the AppCenter the app description looks weird. I think you have to delete line breaks into `<description>` tag in `appdata.xml`

Here is a screenshot:

![image](https://user-images.githubusercontent.com/45366162/53186212-d7353880-3600-11e9-874d-5b337fff963e.png)

**Comment by naaando** [comment]
Hi @NathanBnm , I fixed the translation source files.

About the AppCenter's app description I don't think it is an issue with my file since as XML files and HTML should ignore line breaks.
