### ISSUE TITLE
UI is horrible on KDE

### ISSUE THREAD

**Issue by princenna** [naaando/lyrics#33]
![deepin-screen-recorder_Select area_20190511152117](https://user-images.githubusercontent.com/46909812/57571090-7ba96880-7401-11e9-94ab-c8415b2ca98c.gif)

As you can see there are no controls except for close too. Love your app but also love KDE.

**Comment by naaando** [comment]
Damn, looks really weird. Are you installing the app by flatpak?

I will have a look on it as soon as possible but unfortunatelly my pc broke, I expect to fix it within two months, right now I believe you can fix it by installing the flatpaked app and elementary theme and forcing the app to use the theme.

**Comment by princenna** [comment]
I did install it via flatpak but I don't know how to force the app to use elementary theme.

**Comment by naaando** [comment]
I believe you I'll have to install elementary's theme and pass GTK_THEME environment variable set to elementary's theme when opening the file. I think I'll glue elementary's stylesheets directly into my app to fix this.

**Comment by princenna** [comment]
I'll try that thanks.

**Comment by naaando** [comment]
Good luck, ping me back with the results

Em qui, 6 de jun de 2019 07:17, princenna <notifications@github.com>
escreveu:

**Comment by princenna** [comment]
Sorry I took so long but I ran into an issue with all my flatpak apps so I got frustrated and just uninstalled flatpak, ill try building your app from source.

**Comment by naaando** [comment]
Cool, so will be even easier, you can just customize the css inside data folder the way you like. Weird that you found problems using flatpaks, hope you don't give up on it, seems to be fine stuff. Open another issue if you find struggle building it from source.

**Comment by princenna** [comment]
Thanks will do
